#!/bin/bash

cd ../..

INFINNI_UI_ZIP="InfinniUI.zip"
PACKAGING=".packaging/7z"
FILES="@$PACKAGING/files"
EXCLUDE="@$PACKAGING/exclude"
GRUNTFILE="`pwd`/$PACKAGING/Gruntfile.js"
PACKAGE="`pwd`/$PACKAGING/package.json"

grunt build:{}

rm -rf $INFINNI_UI_ZIP
7z a -tzip $INFINNI_UI_ZIP $FILES -x$EXCLUDE
7z a -tzip $INFINNI_UI_ZIP $GRUNTFILE
7z a -tzip $INFINNI_UI_ZIP $PACKAGE

mkdir -p out/platform
cp -f out/platform.js out/platform/platform.js
7z a -tzip $INFINNI_UI_ZIP out/platform/platform.js

grunt build:{\"mode\"=\"development\"}

mkdir -p out/platform
cp -f out/platform.js out/platform/platform-dev.js
7z a -tzip $INFINNI_UI_ZIP out/platform/platform-dev.js

rm -rf out/platform
