#!/bin/bash

cd ../..

INFINNI_UI_ZIP="InfinniUI.$1.zip"
PACKAGING=".packaging/7z"
FILES="@$PACKAGING/files"
EXCLUDE="@$PACKAGING/exclude"

npm run-script build

rm -rf InfinniUI.*.zip
7z a -tzip $INFINNI_UI_ZIP $FILES -x$EXCLUDE
