InfinniUI.config.lang = 'ru-RU';
InfinniUI.config.maxLengthUrl = 2048;
InfinniUI.config.cacheMetadata = false; //boolean - enable/disable cache | milliseconds
InfinniUI.config.serverUrl = 'http://localhost:9900';
InfinniUI.config.configId = 'PTA';
InfinniUI.config.configName = 'Хабинет';
InfinniUI.config.useLoaderIndicator = true;
InfinniUI.config.serviceUnavailablePage = '/503.html';
InfinniUI.config.faqBaseUrl = "help.habinet.ru";