InfinniUI.config.lang = 'ru-RU';
InfinniUI.config.maxLengthUrl = 2048;
InfinniUI.config.cacheMetadata = false; //boolean - enable/disable cache | milliseconds
InfinniUI.config.serverUrl = 'http://localhost:9900';
//InfinniUI.config.serverUrl = 'http://10.0.0.76:9900';
//InfinniUI.config.serverUrl = 'http://10.222.222.68:9900';
InfinniUI.config.serverUrl = 'http://127.0.0.1:9900';
InfinniUI.config.configId = 'PTA';
InfinniUI.config.configName = 'Регистр беременных';
InfinniUI.config.useLoaderIndicator = true;
